// internal/monitor/process/processbpf_stub.go
//
// Stub types for bpf2go-generated code.
// When eBPF headers are available, delete this file and run: make generate
// The monitors fall back to /proc polling when eBPF load fails at runtime.

package process

import "github.com/cilium/ebpf"

// ProcessObjects contains all eBPF programs and maps after loading.
// In production this is generated by bpf2go from process.bpf.c.
type ProcessObjects struct {
	TracepointSyscallsSysEnterExecve *ebpf.Program
	TracepointSchedSchedProcessFork  *ebpf.Program
	TracepointSyscallsSysEnterPtrace *ebpf.Program
	KprobeKernelClone                *ebpf.Program
	ProcessEvents                    *ebpf.Map
}

func (o *ProcessObjects) Close() {
	for _, p := range []*ebpf.Program{
		o.TracepointSyscallsSysEnterExecve,
		o.TracepointSchedSchedProcessFork,
		o.TracepointSyscallsSysEnterPtrace,
		o.KprobeKernelClone,
	} {
		if p != nil { p.Close() }
	}
	if o.ProcessEvents != nil { o.ProcessEvents.Close() }
}

// LoadProcessObjects loads eBPF programs from the compiled object file.
// Returns an error when eBPF is unavailable; callers fall back to /proc polling.
func LoadProcessObjects(obj *ProcessObjects, opts *ebpf.CollectionOptions) error {
	return &ebpf.VerifierError{Log: []string{"eBPF objects not compiled — run make generate"}}
}
