// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package process

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// LoadProcess returns the embedded CollectionSpec for Process.
func LoadProcess() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_ProcessBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Process: %w", err)
	}

	return spec, err
}

// LoadProcessObjects loads Process and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*ProcessObjects
//	*ProcessPrograms
//	*ProcessMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadProcessObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadProcess()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// ProcessSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ProcessSpecs struct {
	ProcessProgramSpecs
	ProcessMapSpecs
}

// ProcessSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ProcessProgramSpecs struct {
	KprobeKernelClone                *ebpf.ProgramSpec `ebpf:"kprobe_kernel_clone"`
	TracepointSchedSchedProcessFork  *ebpf.ProgramSpec `ebpf:"tracepoint_sched_sched_process_fork"`
	TracepointSyscallsSysEnterExecve *ebpf.ProgramSpec `ebpf:"tracepoint_syscalls_sys_enter_execve"`
	TracepointSyscallsSysEnterPtrace *ebpf.ProgramSpec `ebpf:"tracepoint_syscalls_sys_enter_ptrace"`
}

// ProcessMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ProcessMapSpecs struct {
	CloneFlagsMap *ebpf.MapSpec `ebpf:"clone_flags_map"`
	ProcessEvents *ebpf.MapSpec `ebpf:"process_events"`
}

// ProcessObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadProcessObjects or ebpf.CollectionSpec.LoadAndAssign.
type ProcessObjects struct {
	ProcessPrograms
	ProcessMaps
}

func (o *ProcessObjects) Close() error {
	return _ProcessClose(
		&o.ProcessPrograms,
		&o.ProcessMaps,
	)
}

// ProcessMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadProcessObjects or ebpf.CollectionSpec.LoadAndAssign.
type ProcessMaps struct {
	CloneFlagsMap *ebpf.Map `ebpf:"clone_flags_map"`
	ProcessEvents *ebpf.Map `ebpf:"process_events"`
}

func (m *ProcessMaps) Close() error {
	return _ProcessClose(
		m.CloneFlagsMap,
		m.ProcessEvents,
	)
}

// ProcessPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadProcessObjects or ebpf.CollectionSpec.LoadAndAssign.
type ProcessPrograms struct {
	KprobeKernelClone                *ebpf.Program `ebpf:"kprobe_kernel_clone"`
	TracepointSchedSchedProcessFork  *ebpf.Program `ebpf:"tracepoint_sched_sched_process_fork"`
	TracepointSyscallsSysEnterExecve *ebpf.Program `ebpf:"tracepoint_syscalls_sys_enter_execve"`
	TracepointSyscallsSysEnterPtrace *ebpf.Program `ebpf:"tracepoint_syscalls_sys_enter_ptrace"`
}

func (p *ProcessPrograms) Close() error {
	return _ProcessClose(
		p.KprobeKernelClone,
		p.TracepointSchedSchedProcessFork,
		p.TracepointSyscallsSysEnterExecve,
		p.TracepointSyscallsSysEnterPtrace,
	)
}

func _ProcessClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed process_bpfeb.o
var _ProcessBytes []byte
