// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package file

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// LoadFile returns the embedded CollectionSpec for File.
func LoadFile() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_FileBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load File: %w", err)
	}

	return spec, err
}

// LoadFileObjects loads File and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*FileObjects
//	*FilePrograms
//	*FileMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadFileObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadFile()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// FileSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type FileSpecs struct {
	FileProgramSpecs
	FileMapSpecs
}

// FileSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type FileProgramSpecs struct {
	KprobeSecurityInodeSetattr *ebpf.ProgramSpec `ebpf:"kprobe_security_inode_setattr"`
	KprobeVfsCreate            *ebpf.ProgramSpec `ebpf:"kprobe_vfs_create"`
	KprobeVfsRename            *ebpf.ProgramSpec `ebpf:"kprobe_vfs_rename"`
	KprobeVfsUnlink            *ebpf.ProgramSpec `ebpf:"kprobe_vfs_unlink"`
	KprobeVfsWrite             *ebpf.ProgramSpec `ebpf:"kprobe_vfs_write"`
}

// FileMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type FileMapSpecs struct {
	FileEvents *ebpf.MapSpec `ebpf:"file_events"`
}

// FileObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadFileObjects or ebpf.CollectionSpec.LoadAndAssign.
type FileObjects struct {
	FilePrograms
	FileMaps
}

func (o *FileObjects) Close() error {
	return _FileClose(
		&o.FilePrograms,
		&o.FileMaps,
	)
}

// FileMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadFileObjects or ebpf.CollectionSpec.LoadAndAssign.
type FileMaps struct {
	FileEvents *ebpf.Map `ebpf:"file_events"`
}

func (m *FileMaps) Close() error {
	return _FileClose(
		m.FileEvents,
	)
}

// FilePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadFileObjects or ebpf.CollectionSpec.LoadAndAssign.
type FilePrograms struct {
	KprobeSecurityInodeSetattr *ebpf.Program `ebpf:"kprobe_security_inode_setattr"`
	KprobeVfsCreate            *ebpf.Program `ebpf:"kprobe_vfs_create"`
	KprobeVfsRename            *ebpf.Program `ebpf:"kprobe_vfs_rename"`
	KprobeVfsUnlink            *ebpf.Program `ebpf:"kprobe_vfs_unlink"`
	KprobeVfsWrite             *ebpf.Program `ebpf:"kprobe_vfs_write"`
}

func (p *FilePrograms) Close() error {
	return _FileClose(
		p.KprobeSecurityInodeSetattr,
		p.KprobeVfsCreate,
		p.KprobeVfsRename,
		p.KprobeVfsUnlink,
		p.KprobeVfsWrite,
	)
}

func _FileClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed file_bpfeb.o
var _FileBytes []byte
