// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64

package network

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type NetworkNetEventV4 struct {
	TimestampNs uint64
	EventType   uint32
	Pid         uint32
	Ppid        uint32
	Uid         uint32
	Comm        [16]int8
	SrcIp       uint32
	DstIp       uint32
	SrcPort     uint16
	DstPort     uint16
	Protocol    uint8
	Direction   uint8
	TcpState    uint8
	Pad         uint8
	BytesSent   uint64
	BytesRecv   uint64
	SockCookie  uint64
}

type NetworkNetEventV6 struct {
	TimestampNs uint64
	EventType   uint32
	Pid         uint32
	Ppid        uint32
	Uid         uint32
	Comm        [16]int8
	SrcIp       [16]uint8
	DstIp       [16]uint8
	SrcPort     uint16
	DstPort     uint16
	Protocol    uint8
	Direction   uint8
	TcpState    uint8
	Pad         uint8
	BytesSent   uint64
	BytesRecv   uint64
	SockCookie  uint64
}

// LoadNetwork returns the embedded CollectionSpec for Network.
func LoadNetwork() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_NetworkBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Network: %w", err)
	}

	return spec, err
}

// LoadNetworkObjects loads Network and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*NetworkObjects
//	*NetworkPrograms
//	*NetworkMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadNetworkObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadNetwork()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// NetworkSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type NetworkSpecs struct {
	NetworkProgramSpecs
	NetworkMapSpecs
}

// NetworkSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type NetworkProgramSpecs struct {
	FentryTcpClose     *ebpf.ProgramSpec `ebpf:"fentry_tcp_close"`
	FentryTcpConnect   *ebpf.ProgramSpec `ebpf:"fentry_tcp_connect"`
	FexitInetCskAccept *ebpf.ProgramSpec `ebpf:"fexit_inet_csk_accept"`
	KprobeUdpRecvmsg   *ebpf.ProgramSpec `ebpf:"kprobe_udp_recvmsg"`
	KprobeUdpSendmsg   *ebpf.ProgramSpec `ebpf:"kprobe_udp_sendmsg"`
	TpInetSockSetState *ebpf.ProgramSpec `ebpf:"tp_inet_sock_set_state"`
}

// NetworkMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type NetworkMapSpecs struct {
	ActiveConnsV4 *ebpf.MapSpec `ebpf:"active_conns_v4"`
	ActiveConnsV6 *ebpf.MapSpec `ebpf:"active_conns_v6"`
	NetworkEvents *ebpf.MapSpec `ebpf:"network_events"`
}

// NetworkObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadNetworkObjects or ebpf.CollectionSpec.LoadAndAssign.
type NetworkObjects struct {
	NetworkPrograms
	NetworkMaps
}

func (o *NetworkObjects) Close() error {
	return _NetworkClose(
		&o.NetworkPrograms,
		&o.NetworkMaps,
	)
}

// NetworkMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadNetworkObjects or ebpf.CollectionSpec.LoadAndAssign.
type NetworkMaps struct {
	ActiveConnsV4 *ebpf.Map `ebpf:"active_conns_v4"`
	ActiveConnsV6 *ebpf.Map `ebpf:"active_conns_v6"`
	NetworkEvents *ebpf.Map `ebpf:"network_events"`
}

func (m *NetworkMaps) Close() error {
	return _NetworkClose(
		m.ActiveConnsV4,
		m.ActiveConnsV6,
		m.NetworkEvents,
	)
}

// NetworkPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadNetworkObjects or ebpf.CollectionSpec.LoadAndAssign.
type NetworkPrograms struct {
	FentryTcpClose     *ebpf.Program `ebpf:"fentry_tcp_close"`
	FentryTcpConnect   *ebpf.Program `ebpf:"fentry_tcp_connect"`
	FexitInetCskAccept *ebpf.Program `ebpf:"fexit_inet_csk_accept"`
	KprobeUdpRecvmsg   *ebpf.Program `ebpf:"kprobe_udp_recvmsg"`
	KprobeUdpSendmsg   *ebpf.Program `ebpf:"kprobe_udp_sendmsg"`
	TpInetSockSetState *ebpf.Program `ebpf:"tp_inet_sock_set_state"`
}

func (p *NetworkPrograms) Close() error {
	return _NetworkClose(
		p.FentryTcpClose,
		p.FentryTcpConnect,
		p.FexitInetCskAccept,
		p.KprobeUdpRecvmsg,
		p.KprobeUdpSendmsg,
		p.TpInetSockSetState,
	)
}

func _NetworkClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed network_bpfel.o
var _NetworkBytes []byte
